# Generated by Django 4.2 on 2023-04-04 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0003_alter_item_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_sold',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('in stock', 'В наличии'), ('out of stock', 'Нет в наличии')], default='out of stock', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
