# Generated by Django 4.2 on 2023-04-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_item_is_sold_item_status_item_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='categories',
        ),
    ]
