# Generated by Django 4.2 on 2023-04-05 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sub_comment',
        ),
    ]
