# Generated by Django 4.2 on 2023-04-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_remove_comment_sub_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
