# Generated by Django 4.2 on 2023-04-05 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
